### ISSUE TITLE
as a user I would like to be able to create a tree map as a type of mindmap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#141]
![image](https://user-images.githubusercontent.com/3675043/130168017-fbcd6447-6b09-47dc-81e0-43bd2a26f80a.png)

**Comment by b-solution** [comment]
<img width="736" alt="Screenshot 2021-11-08 at 3 24 16 PM" src="https://user-images.githubusercontent.com/5988861/140726431-01bf3368-f8c1-4f0c-8c3c-606f9b17f39c.png">

<img width="1435" alt="Screenshot 2021-11-08 at 3 24 48 PM" src="https://user-images.githubusercontent.com/5988861/140726478-88c7bdbc-7f9b-4161-8bcd-6269640a3e34.png">

<img width="674" alt="Screenshot 2021-11-08 at 3 26 01 PM" src="https://user-images.githubusercontent.com/5988861/140726567-67fc1853-1fdc-40ca-bfa2-964eb6a2e352.png">

<img width="694" alt="Screenshot 2021-11-08 at 3 26 56 PM" src="https://user-images.githubusercontent.com/5988861/140726636-eff7ea01-d337-495c-a2e0-a548e9f9dccd.png">

<img width="679" alt="Screenshot 2021-11-08 at 3 27 14 PM" src="https://user-images.githubusercontent.com/5988861/140726662-96b52a68-79e2-4fd7-9ae9-e269885b29d2.png">

<img width="1427" alt="Screenshot 2021-11-08 at 3 28 41 PM" src="https://user-images.githubusercontent.com/5988861/140726740-bb597048-965c-4135-bb41-cb4f1210f674.png">

**Comment by b-solution** [comment]
@bluenevus Please take a look.

**Comment by bluenevus** [comment]
awsome.  looking forward to trying this out
