### ISSUE TITLE
as a user, I would like a kanban board as a type of mindmap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#144]
the user defines the lanes

then they can put "post it notes" in the lanes to brainstorm

![image](https://user-images.githubusercontent.com/3675043/130168880-09accb59-3e89-455b-b327-63aa537c4974.png)

similar to this but much easier to determine how to add a lane and to add post it notes.  Its hard for people to figure that out but I do like how you can drag and drop it anywhere and how it feels like a virtual whiteboard

http://scrumblr.ca/bilel

**Comment by b-solution** [comment]
@bluenevus Can you please provide these icon images? OR should I used random  from internet?

**Comment by bluenevus** [comment]
those were just examples.  We just need to get the related icons

**Comment by b-solution** [comment]
<img width="991" alt="Screenshot 2021-11-12 at 7 03 00 PM" src="https://user-images.githubusercontent.com/5988861/141479264-dcc80bb2-20fe-41a6-ac0e-863c451449b1.png">
