### ISSUE TITLE
as a user, I would like a "delete" function on any mindmap I'm working with a confirmation message

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#153]
sometimes a whiteboard is like well a whiteboard where you want to "erase" what you did.  So there needs to be a "delete" or erase" board function on any mindmap type so if its "private" they can then "erase" or "delete" it when they are done with a confirmation message

**Comment by b-solution** [comment]
<img width="1438" alt="Screenshot 2021-11-23 at 4 54 53 PM" src="https://user-images.githubusercontent.com/5988861/143020274-1fabc20d-3a9e-4492-b8b7-f6c41063f14b.png">

<img width="1429" alt="Screenshot 2021-11-23 at 4 57 14 PM" src="https://user-images.githubusercontent.com/5988861/143020704-bb8e0f5c-261b-4708-b351-3d76fb2bf535.png">

<img width="1437" alt="Screenshot 2021-11-23 at 4 54 10 PM" src="https://user-images.githubusercontent.com/5988861/143020738-93ab73b3-af5d-4152-b703-825558d36b38.png">

<img width="785" alt="Screenshot 2021-11-23 at 4 55 44 PM" src="https://user-images.githubusercontent.com/5988861/143020776-0e58b28e-bc7f-42f9-ad6c-2fc64cfceb0a.png">

<img width="728" alt="Screenshot 2021-11-23 at 4 56 01 PM" src="https://user-images.githubusercontent.com/5988861/143020828-fa198ce8-8571-41ee-ad5e-11f72e320cbf.png">


 delete mind map functionality.
