### ISSUE TITLE
as a user, I would like to password protect a mindmap

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#154]
for any type of mindmap, I would like to be able to mark it as private and apply a password.  This password is only for that mindmap and not for ALL mindmaps...just the one they are marking private.  This will password protect the mindmap they created and they can share this mindmap with a password if neccessary.  They should also be able to change that password or remove it should they choose

**Comment by b-solution** [comment]
Added a button to make mindmap private by adding password.
<img width="1439" alt="Screenshot 2021-11-12 at 4 15 01 PM" src="https://user-images.githubusercontent.com/5988861/141458689-5d5b774b-3480-4e92-97f5-1a7ed5f3ff4b.png">

Enter Password modal:
<img width="846" alt="Screenshot 2021-11-12 at 4 15 26 PM" src="https://user-images.githubusercontent.com/5988861/141458703-67b9f855-9b82-4306-8bfe-a5d8fa8702f6.png">

Successfully password added modal:
<img width="851" alt="Screenshot 2021-11-12 at 4 15 39 PM" src="https://user-images.githubusercontent.com/5988861/141458712-7f1666c8-ae80-4a4c-a501-c5be82238751.png">

Verify password modal:
<img width="817" alt="Screenshot 2021-11-12 at 4 16 28 PM" src="https://user-images.githubusercontent.com/5988861/141458718-0822db7d-63f2-43da-84bc-cd196b33f570.png">

Update password modal:
<img width="836" alt="Screenshot 2021-11-12 at 4 19 17 PM" src="https://user-images.githubusercontent.com/5988861/141459011-e93daab7-46d4-4761-8ca4-e65884ba88e6.png">

**Comment by b-solution** [comment]
Password protect functionality added for app map (mindmap, kanban, treemap).
