### ISSUE TITLE
User should be able to Sign In with Office 365

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#155]
Screenshot Example

![mindmap_signIn_office365](https://user-images.githubusercontent.com/11938477/140796894-9483a10a-f574-46ba-94c3-cc31bf217145.png)

![Office365_SignIn_failed](https://user-images.githubusercontent.com/11938477/140796904-c3bf2d68-74c1-41d0-8b03-a97adc900ce6.png)

**Comment by bluenevus** [comment]
we are shutting down login
