### ISSUE TITLE
User should be able to Sign In with Google

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#156]
Screenshot Example

![mindmap_signIn_google](https://user-images.githubusercontent.com/11938477/140797013-498287fd-c1a3-4a2f-95e7-0b3a93960ffa.png)

![Google_SignIn_Failed](https://user-images.githubusercontent.com/11938477/140797021-57f0bb16-836c-46dd-b640-1ce770eacd64.png)

**Comment by bluenevus** [comment]
we are shutting down login
