### ISSUE TITLE
remove or hide login.  revert to the way it worked previously

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#157]
it should behave like so 

https://etherpad.wikimedia.org/

**Comment by bluenevus** [comment]
we may have login in the future maybe as a configuration item where it can be enabled  but the default behavior is like so https://etherpad.wikimedia.org/

**Comment by b-solution** [comment]
<img width="1440" alt="Screenshot 2021-11-12 at 4 13 23 PM" src="https://user-images.githubusercontent.com/5988861/141458230-bfa58a41-ded4-48aa-862d-f4f0836c2b7c.png">
