### ISSUE TITLE
Fix the menu icons for Cut, Paste, and Export Word when mindmap screen displays after Show icon (eye) clicked on File Manager

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#158]
Screenshot Example

![cut_paste_icons_different_missing_Export_Word_icon_after_show_clicked_from_File_Manager_screen](https://user-images.githubusercontent.com/11938477/140801623-4c2c3e9a-f5ea-4f86-ab4a-7780590fb9d2.png)

![file_manager_show_icon_eye_click](https://user-images.githubusercontent.com/11938477/140801843-1c8329ff-9e62-451a-8d28-bf3a122d7297.png)

**Comment by b-solution** [comment]
<img width="1346" alt="Screenshot 2021-11-18 at 1 32 58 PM" src="https://user-images.githubusercontent.com/5988861/142379983-6598dedb-dcb1-4559-b251-3ea701981d30.png">
<img width="1439" alt="Screenshot 2021-11-18 at 1 33 31 PM" src="https://user-images.githubusercontent.com/5988861/142380005-f909b91d-3803-4c56-b61a-48d97e10c2db.png">

**Comment by LAlexMHllc** [comment]
Reopening, since not able to test due to Issue #191

**Comment by LAlexMHllc** [comment]
Closing, since File Manager will not be used at this time.
