### ISSUE TITLE
File Manager screen: Column header should be "Share As" to match form

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#159]
Screenshot Example

![file_manager_table_header_should_be_Share-As](https://user-images.githubusercontent.com/11938477/140804694-0e4ad6cf-0638-4bf5-9488-cbd04c6ac242.png)

![edit_mindmap_form_Share-As_label](https://user-images.githubusercontent.com/11938477/140804919-3bdb4560-27a8-4507-85f1-a96fa488bbef.png)

**Comment by bluenevus** [comment]
there will no longer be users in mindmaps so obe
