### ISSUE TITLE
Edit mindmap form: When Share As has only_me or public_link selected, then Share With should have none selected

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#161]
Screenshot Example

![edit_mindmap_form_when_Share_As_has_only-me_or_public-link_then_Share_With_not-selected](https://user-images.githubusercontent.com/11938477/140806130-f5d1b1dc-878e-49bb-b144-133c07178b18.png)

**Comment by bluenevus** [comment]
there will no longer be users in mindmaps so this is OBE
