### ISSUE TITLE
mindmaps not working realtime between two or more users

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#164]
![image](https://user-images.githubusercontent.com/3675043/141486207-3c2744ea-648e-4edb-a39e-74e61729e71b.png)

**Comment by b-solution** [comment]
@bluenevus  It's working for me, can you please share the Redis-server status ?

**Comment by bluenevus** [comment]
@b-solution
![redis](https://user-images.githubusercontent.com/3675043/143261596-51b623f4-1cf4-4cdc-8389-5e1adf805aee.png)

its running.  Is there some special configuration in the app I need to do.  Its running on centos 8 with just puma, ruby 2.6.6p146
