### ISSUE TITLE
Password Form should include Password Confirm

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#169]
Screenshot Example

![password_form_should_include_password_confirm](https://user-images.githubusercontent.com/11938477/141490463-1f0c1801-34b6-4520-a20a-4c8d9f2393be.png)

**Comment by b-solution** [comment]
<img width="826" alt="Screenshot 2021-11-18 at 1 41 15 PM" src="https://user-images.githubusercontent.com/5988861/142381172-2382326a-9705-4d34-bef9-ba253ca332df.png">
<img width="812" alt="Screenshot 2021-11-18 at 1 41 33 PM" src="https://user-images.githubusercontent.com/5988861/142381179-86901133-bc6b-4053-a199-0d64eaea096f.png">
