### ISSUE TITLE
Kanban - Add a Task button should remain above listing

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#172]
Screenshot Example

![add_task_button_should_remain_above_listing](https://user-images.githubusercontent.com/11938477/141492552-73361035-0168-437e-897d-3b51d9da98bf.png)

**Comment by b-solution** [comment]
<img width="1432" alt="Screenshot 2021-11-18 at 1 48 11 PM" src="https://user-images.githubusercontent.com/5988861/142382281-0c5f1313-58e9-484a-b6c5-17383a27474d.png">
