### ISSUE TITLE
default the kanban stages so they have a starting point

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#173]
by default every new kanban should look like this
![image](https://user-images.githubusercontent.com/3675043/141492198-dcdca861-6798-4457-9226-95049bb2275d.png)

of course this is related to being able to move the columns around and different order by drag and drop

**Comment by b-solution** [comment]
![Uploading Screenshot 2021-11-25 at 5.54.02 PM.png…]()

**Comment by b-solution** [comment]
https://user-images.githubusercontent.com/5988861/143581107-d4a27670-b4aa-4201-a6fd-df5420025b23.mov
