### ISSUE TITLE
Kanban - Reduce the number of clicks to edit/delete column Title

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#174]
Screenshot Example

![edit-delete-column-title-function](https://user-images.githubusercontent.com/11938477/141498069-a86bcbcc-c012-4dff-a926-00ea97bd714a.png)

**Comment by bluenevus** [comment]
Direct entry in the stage field

Direct form entry directly adding a task with the field to dynamically grow to wrap text

Big red X to delete the task.  Big red X to delete the stage

Adding a stage simply adds one to the end of the stages where they can then directly enter, give it a name and drag and drop it in the order they want

the purpose is quick, dirty direct entry, direct action reduce dialogs, reduce clicks and wysiwyg

**Comment by b-solution** [comment]
Add Stage:
<img width="1439" alt="Screenshot 2021-11-25 at 4 12 13 PM" src="https://user-images.githubusercontent.com/5988861/143431707-eeb21023-feca-472a-8c5b-5ee7ad2ded61.png">

Edit Task:
<img width="311" alt="Screenshot 2021-11-25 at 4 13 57 PM" src="https://user-images.githubusercontent.com/5988861/143431731-3484524e-8967-4a54-b7f8-df31dde704a2.png">

Edit Stage:
<img width="339" alt="Screenshot 2021-11-25 at 4 14 12 PM" src="https://user-images.githubusercontent.com/5988861/143431735-d0f3d686-6831-45f9-b8d0-7748118ec6e1.png">

Delete Task:
<img width="378" alt="Screenshot 2021-11-25 at 4 14 26 PM" src="https://user-images.githubusercontent.com/5988861/143431791-289f52b5-abed-4e26-9796-d224ad0e8275.png">

Delete Stage:
<img width="425" alt="Screenshot 2021-11-25 at 4 14 40 PM" src="https://user-images.githubusercontent.com/5988861/143431797-af41ee3a-cf26-4062-a67b-ed20c9324c12.png">
