### ISSUE TITLE
Kanban - Should be able to edit/delete Task without popup menu

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#175]
Reduce the number of clicks to edit/delete Task.
Should be able to directly edit Task on column.
Display "X" to delete task.

Screenshot Example

![should_be_able_to_edit_delete_task_without_popup_menu](https://user-images.githubusercontent.com/11938477/141499762-878bfd83-7151-4c6f-91a4-236afe3bbeab.png)

**Comment by bluenevus** [comment]
directly enter and as he title gets longer, the field wordwraps and the space increases automatically

to delete the card, there should be a red X with a confirmation dialog

**Comment by b-solution** [comment]
<img width="1421" alt="Screenshot 2021-11-18 at 2 43 59 PM" src="https://user-images.githubusercontent.com/5988861/142390991-78e0d432-4adc-47ed-8b69-f9ac34f92691.png">
