### ISSUE TITLE
Tree Map - User should be able to click/edit Tree Map Title to directly update

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#178]
Instead of user clicking "Update Tree Map" button and popup form displaying, user should be able to click the Title to directly update.

Screenshot Example

![update_tree_map_title_by_click_direct_update_instead_of_button_with_popup_form](https://user-images.githubusercontent.com/11938477/141507120-588f876a-2076-40be-a100-b1e2a1c9e950.png)

**Comment by b-solution** [comment]
<img width="1432" alt="Screenshot 2021-11-26 at 6 30 04 PM" src="https://user-images.githubusercontent.com/5988861/143588465-c8fc337c-4de3-4655-af55-e3df7c8d08ad.png">
