### ISSUE TITLE
Tree Map - User should be able to Edit/Delete Node without clicking Update Node and using popup form

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#179]
User should be able to edit node Title directly by clicking Title.
User should be able to click "X" and confirm/delete node.

Screenshot Example

![update_node_title_background_by_click_direct_update_instead_of_button_with_popup_form](https://user-images.githubusercontent.com/11938477/141515918-2be74686-b675-49af-9119-377a468dfbd8.png)

User should be able to click node background to update color.

Screenshot Example

![display_color_modal_when_user_clicks_node_background](https://user-images.githubusercontent.com/11938477/141527051-c3d5f910-ff37-44e8-b30c-ab101f05e062.png)

**Comment by LAlexMHllc** [comment]
NOTE: When Color Selector displays, the current background should be selected along with the HEXNOTE: When Color Selector displays, the current background should be selected along with the HEX

**Comment by b-solution** [comment]
<img width="1439" alt="Screenshot 2021-11-26 at 6 17 45 PM" src="https://user-images.githubusercontent.com/5988861/143587681-e4b715f9-cab8-4ea6-8a83-e7c9171934e7.png">

<img width="1440" alt="Screenshot 2021-11-26 at 6 21 34 PM" src="https://user-images.githubusercontent.com/5988861/143587707-b3e56474-1a25-4961-ba7f-c1deb872e53c.png">

<img width="784" alt="Screenshot 2021-11-26 at 6 23 24 PM" src="https://user-images.githubusercontent.com/5988861/143587727-772ccaed-eca9-47e1-9f05-4e1c2425937e.png">
