### ISSUE TITLE
User should be able to click the Tree Map background, then select color to update.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#180]
Currently, the user can not update the Tree Map background color.

Screenshot Example

![should_be_able_to_update_background_color_of_tree_map_by_clicking_selecting_color](https://user-images.githubusercontent.com/11938477/141519551-3a63356c-b773-4725-9dc8-2f6c7d1f427b.png)

User should be able to click the background, then select color from background color modal.
Screenshot Example

![background_color_selector](https://user-images.githubusercontent.com/11938477/141529746-23659798-9cb7-4886-abfc-b136310ab35e.png)

**Comment by LAlexMHllc** [comment]
NOTE: When Color Selector displays, the current background should be selected along with the HEX

**Comment by b-solution** [comment]
<img width="1439" alt="Screenshot 2021-11-26 at 6 17 45 PM" src="https://user-images.githubusercontent.com/5988861/143587195-35d1f721-a16f-4861-9af2-c96b4003ab84.png">
