### ISSUE TITLE
Tree Map - User should be able to Delete node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#182]
Clicking "Delete" on Update Node form did not delete node.
Screenshot Example

![update_node_clicking_delete_node_did_not_delete](https://user-images.githubusercontent.com/11938477/141526709-62530693-b00d-40e0-b0db-4294e39c7f6c.png)

**Comment by LAlexMHllc** [comment]
NOTE: See Issue #179 - to include "X" confirm delete

**Comment by b-solution** [comment]
<img width="1421" alt="Screenshot 2021-11-18 at 3 34 27 PM" src="https://user-images.githubusercontent.com/5988861/142399476-6eebf2bd-505e-41b1-b235-e2ab1135142b.png">

<img width="687" alt="Screenshot 2021-11-18 at 3 34 47 PM" src="https://user-images.githubusercontent.com/5988861/142399492-b72115cb-b70c-489c-80df-8935fd22644b.png">

<img width="1428" alt="Screenshot 2021-11-18 at 3 35 10 PM" src="https://user-images.githubusercontent.com/5988861/142399498-48d0a773-40d8-400d-af0d-23c45d09c8df.png">
