### ISSUE TITLE
Should be able to export Tree Map

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#184]

**Comment by b-solution** [comment]
<img width="1436" alt="Screenshot 2021-11-30 at 2 28 54 PM" src="https://user-images.githubusercontent.com/5988861/144021224-9609477f-247b-41a2-bd83-851a57655408.png">

![17yrtywOiAN71bS](https://user-images.githubusercontent.com/5988861/144021272-8cd86858-4f22-4c0f-9931-7173aff05eae.png)
