### ISSUE TITLE
Should be able to export Kanban

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#185]

**Comment by b-solution** [comment]
Click on Export button:
<img width="1428" alt="Screenshot 2021-11-30 at 2 51 37 PM" src="https://user-images.githubusercontent.com/5988861/144025249-8232775d-84ae-45e1-9321-17c108e96fbb.png">

Download below image:
![sLgVMblGQfOcHTa](https://user-images.githubusercontent.com/5988861/144025304-11537a21-de32-4696-9b9b-e258a739fef4.png)
