### ISSUE TITLE
Color Picker modal should remain open until user closes

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#202]
Difficult for user to make desired selection before modal automatically closes
Screenshot Example

![color_picker_modal_should_remain_open_until_user_closes](https://user-images.githubusercontent.com/11938477/143611382-21f4ccd6-d621-4a09-9daf-78efeed488ce.png)

**Comment by b-solution** [comment]
<img width="1425" alt="Screenshot 2021-11-30 at 2 05 25 PM" src="https://user-images.githubusercontent.com/5988861/144017523-6ea1209c-6ad8-4f99-9ae5-2fa8205cf06e.png">
