### ISSUE TITLE
Tree Map - For each node, should include a "+" before each delete "x" icon; when clicked, add a child node.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#207]
Remove "+ Add Node" button and Add Node Tree Map modal.
Screenshot Example

![tree_map_remove_add_node_button_and_modal](https://user-images.githubusercontent.com/11938477/144088694-1f93fedf-f4b1-4f3d-81f4-c6f417301417.png)

User will click the "+" on the parent node.
Screenshot Example

![click_plus_to_add_child_node](https://user-images.githubusercontent.com/11938477/144095211-1fb3f499-1592-4ab1-8048-9e4c16ef31d7.png)

A child node will display with default textbox with placeholder, and should be on focus. User should input Title on new node. User should be able to change node background color with Color Picker.
Screenshot Example

![child_node_added_after_plus_clicked_default_text](https://user-images.githubusercontent.com/11938477/144097114-d2e71f84-9147-489b-85e8-e69eae468cd8.png)

NOTE: New node should not be saved without non-blank Title.

**Comment by b-solution** [comment]
<img width="1436" alt="Screenshot 2021-12-03 at 7 33 10 PM" src="https://user-images.githubusercontent.com/5988861/144620335-e056b880-e15e-4b45-848e-a5a19393d186.png">
