### ISSUE TITLE
Tree Map - Update node Title should stick

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#209]
Changed Title, then clicked Reload. Updated Title did not stick.
Screenshot Example

![tree_map_changed_node_Title_clicked_Reload_new_title_did_not_stick](https://user-images.githubusercontent.com/11938477/144101891-06d05ff0-8df1-45a3-ac97-5815430e0afe.png)

--------------------------------------------------------------------------------------------------------------------------

Changed Title, then clicked MH logo. Updated Title did not stick.
Screenshot Example

![tree_map_changed_node_Title_clicked_MH_logo_new_title_did_not_stick](https://user-images.githubusercontent.com/11938477/144101951-56cb1b6a-235c-40c2-8634-1cf93082a89a.png)

**Comment by b-solution** [comment]
<img width="1435" alt="Screenshot 2021-12-02 at 4 40 37 PM" src="https://user-images.githubusercontent.com/5988861/144418234-ce2f17e7-6360-4dc6-8bb7-8f08f79b21df.png">
<img width="1434" alt="Screenshot 2021-12-02 at 4 41 25 PM" src="https://user-images.githubusercontent.com/5988861/144418258-00ec5813-40b3-48a1-b8a9-80b1448ca373.png">
<img width="1420" alt="Screenshot 2021-12-02 at 4 50 37 PM" src="https://user-images.githubusercontent.com/5988861/144418263-eaa3b583-3abc-434e-b846-976de8d25034.png">
