### ISSUE TITLE
Tree Map - clicking MH logo should display the Save Map Key modal (just like mindmap screen)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#210]
Screenshot Example

![save_map_key_modal](https://user-images.githubusercontent.com/11938477/144105244-48be2bea-d04f-4e9c-ae90-7d81286f3de4.png)

**Comment by b-solution** [comment]
<img width="1436" alt="Screenshot 2021-12-02 at 5 06 00 PM" src="https://user-images.githubusercontent.com/5988861/144418972-ffd813a4-16d3-495c-84b8-8e742c445585.png">
