### ISSUE TITLE
Kanban Map - clicking MH logo should display the Save Map Key modal (just like mindmap screen)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#211]
Screenshot Example

![save_map_key_modal](https://user-images.githubusercontent.com/11938477/144105347-93eca7dd-d4f5-4294-819b-618ce662db9e.png)

**Comment by b-solution** [comment]
<img width="1431" alt="Screenshot 2021-12-02 at 5 05 43 PM" src="https://user-images.githubusercontent.com/5988861/144418995-e57507c1-96de-4fd6-8810-ae5634e7a4ac.png">
