### ISSUE TITLE
Tree Map - clicking "x" on a node should display Confirm Delete in Firefox

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#215]

**Comment by b-solution** [comment]
@LAlexMHllc It's working fine for me on Firefox, please share screenshot or console log with me if you still face this issue.

<img width="1280" alt="Screenshot 2021-12-02 at 8 41 56 PM" src="https://user-images.githubusercontent.com/5988861/144454604-74152140-aebe-4145-8820-75b269889b45.png">

**Comment by LAlexMHllc** [comment]
Closing, since functioning correctly after last update
