### ISSUE TITLE
Should validate Password not blank(s); it saved, and now map is inaccessible.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#218]
Screenshot Example

![password_should_not_save_with_blanks](https://user-images.githubusercontent.com/11938477/144453142-56a3d079-aa9f-4471-8fa4-1ac748537bcd.png)

![password_should_not_save_with_blanks_mindmap_becomes_inaccessible](https://user-images.githubusercontent.com/11938477/144453170-67366e13-c7c4-403d-bf78-6cb12ba9a1c1.png)

**Comment by b-solution** [comment]
@LAlexMHllc I'm considering blank/space not allowed in password field.
