### ISSUE TITLE
Sometimes missing "Central Idea" node when a map is created.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#33]
Screenshot Example

![central_idea_sometimes_missing_new_from_new_mindmap](https://user-images.githubusercontent.com/11938477/66600209-0807b500-eb73-11e9-9579-5f76390cb042.jpg)

**Comment by bluenevus** [comment]
if its an existing mindmap you previously created.  you have to move the canvas.  if its not a new canvas, it should show up in the center.
