### ISSUE TITLE
Need consistent default position of Central Idea node when mindmap is created.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mindmap#40]
Sometimes Central Idea node can not be seen, unless browser is zoomed out.

Screenshot Example

![fix_position_central_idea](https://user-images.githubusercontent.com/11938477/66856691-c0f33880-ef53-11e9-9ad4-b95e83856f23.jpg)

**Comment by bluenevus** [comment]
It also doesn't look centered they way it should be

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
