### ISSUE TITLE
after hitting cut, it removes the text but the node remains until you manually refresh the screen

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#43]
![image](https://user-images.githubusercontent.com/3675043/67957689-5d604080-fbcc-11e9-8084-10e70eb37721.png)

then refresh manually

then 

![image](https://user-images.githubusercontent.com/3675043/67957716-68b36c00-fbcc-11e9-9bd2-33a0a2b06804.png)

**Comment by LAlexMHllc** [comment]
Note: This also happened to me in Firefox. In Chrome, after Cut clicked, the focused node with text still displayed until refresh.
