### ISSUE TITLE
words overlap on the lines

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#44]
![image](https://user-images.githubusercontent.com/3675043/67964270-5e966b00-fbd6-11e9-9830-486bf814a9d4.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![words_still_overlap](https://user-images.githubusercontent.com/11938477/68789659-e25b4900-0613-11ea-8cc1-2db67a8bda74.jpg)
