### ISSUE TITLE
can we make the all the icons clickable if they show up; when clicked the panel displays

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mindmap#64]
![image](https://user-images.githubusercontent.com/3675043/68240312-ae13d700-ffda-11e9-8763-41cb66ad50aa.png)

**Comment by LAlexMHllc** [comment]
When the description icon is clicked, display the panel with the Description tab shown. When the files icon is clicked, display the panel with the Files tab shown.

**Comment by bilel-kedidi** [comment]
this is done
